
---------------------------------------------------------
--  This code is generated by Terasic System Builder
--  
--  Group 4 has 3 members:
--    Le Thanh Hai       1851027
--    Nguyen Hoang Tuan  1851018
--    Dang Vu Kim Ky     1812744
---------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;

entity UART_v1 is
port
(

	------------ CLOCK ------------
	clk             	: in    	std_logic;

	------------ IN ------------
	CS                : in    	std_logic;
	datain				: in		std_logic_vector(7 downto 0);
	reset        		: in    	std_logic;
	WR_en					: in    	std_logic;
   addr 					: in     std_logic_vector(2 downto 0);
	------------ OUT ------------
	Tx 					: buffer std_logic;
	busy					: buffer std_logic;
	done_trans			: out    std_logic;
	done_reiceive		: out    std_logic;
	error					: out    std_logic;
	data_received		: out		std_logic_vector(7 downto 0)
	--LEDR            	: out   	std_logic_vector(9 downto 0)
);

end entity;



---------------------------------------------------------
--  Structural coding
---------------------------------------------------------


architecture rtl of UART_v1 is
signal w_baud_clk,w_temp,w_Tx,w_busy,w_done_trans,w_done_reiceive,w_error	: std_logic;
component UART_IP is
  port
  (    
	clk        	      : in    	std_logic;
	CS						: in    	std_logic;
	WR_en					: in    	std_logic;
	data  				: in		std_logic_vector(7 downto 0);
	reset        		: in    	std_logic;
	addr 					: in     std_logic_vector(2 downto 0);
	Tx            		: out std_logic;
	busy          		: out std_logic;
	baud_clk				: out std_logic;
   done			  		: out std_logic	
  );
end component;

component UART_receiver is
  port
  ( 
	--clk           : in std_logic;
	baud_clk      : in std_logic;
	reset         : in std_logic;
	Rx            : in std_logic;
	busy          : in std_logic;
	data_trans    : out std_logic_vector(7 downto 0);	
	error         : out std_logic;
	--done_temp     : out std_logic;
   done			  : buffer std_logic
  );
end component;

begin

-- body --
--Transmitter: UART_transmitter port map (datain,SW(0),CLOCK_50,reset,Tx,busy,done);
Transmitter: UART_IP port map (clk,CS,WR_en,datain,reset,addr,Tx,busy,w_baud_clk,done_trans);
Receiver: UART_receiver port map (w_baud_clk,reset,Tx,busy,data_received,error,done_reiceive);
end rtl;



